### PR TITLE
Improved react-native-web-support.

### PR DESCRIPTION
**Pull request by cawfree**
Hey, [mxck](https://github.com/mxck)!

Really great work on this repo, it's structured like a dream. Just one thing; I noticed that react-native-web's handling of the modal didn't work; it would initialize as opened and once closed, fail to respond to subsequent requests.

Anyway, the workaround for this would be to conditionally include the `Modal` in the returned JSX for the `Menu`; this allows it to reset back to normal on the web. 

These changes will have no effect on Android or iOS.

### CODE REVIEW

**Comment by mxck** [comment]
@cawfree hi! Just try to test you changes, but it seems doesn't work to me. I just see little dot below menu button (see screenshot).
Снимок экрана 2019-08-13 в 19 34 01
I use expo to run web version of example app in readme.md.
Maybe I'm doing something wrong? :)

**Comment by cawfree** [comment]
Oh really? Hm. I've seen that if a container uses `overflow: 'hidden'`, the Modal content doesn't get rendered on Web. Strange! I'll keep looking into this. Thanks again!

**Comment by cawfree** [comment]
Hey @mxck, thanks for your help. I've been doing some experimentation with web's `Modal` outside of this project, and it doesn't feel like it's a fix that should take place in this library, and instead be implemented somewhere further upstream. Sorry for the distraction! 

Again, thanks for the awesome codebase. It really helped with [this project](https://github.com/cawfree/react-native-simple-date-picker)!

**Comment by mxck** [comment]
@cawfree no problem! 👍

**Pull request closed without merging**
