### PR TITLE
MenuItem accepts testID prop

### LINKED ISSUE #34: Pass testID props to Menu and MenuItems
Hi guys,

Thanks for a cool menu.

Would you consider allowing passing of testID props to the Menu and MenuItem. This is useful for E2E testing with Detox. 

I realise this might be an edge use case and am happy to submit a PR.

Cheers,
Shaun

### PR DESCRIPTION
**Pull request by shaunsaker**
# Description

Added testID prop to MenuItem. This is useful for E2E testing with [Detox](https://github.com/wix/detox).

Fixes #34 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested with Detox spec and iPhone 7 simulator.

### CODE REVIEW

**Comment by mxck** [comment]
@shaunsaker thx! Can you add `testID` to Menu component also?

**Comment by shaunsaker** [comment]
@mxck Done!

**Comment by mxck** [comment]
@shaunsaker 👍

**Comment by shaunsaker** [comment]
Epic, thanks @mxck !

**Comment by shaunsaker** [comment]
@mxck When will you be publishing the new version to npm?

**Comment by mxck** [comment]
@shaunsaker on Monday :)

**Comment by mxck** [comment]
@shaunsaker done.

**Comment by shaunsaker** [comment]
@mxck Awesome, thanks for letting me know!

**Pull request merged**
